/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package haskellwebapp2-0.1.0.0 */
#ifndef VERSION_haskellwebapp2
#define VERSION_haskellwebapp2 "0.1.0.0"
#endif /* VERSION_haskellwebapp2 */
#ifndef MIN_VERSION_haskellwebapp2
#define MIN_VERSION_haskellwebapp2(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_haskellwebapp2 */

/* package aeson-1.4.2.0 */
#ifndef VERSION_aeson
#define VERSION_aeson "1.4.2.0"
#endif /* VERSION_aeson */
#ifndef MIN_VERSION_aeson
#define MIN_VERSION_aeson(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_aeson */

/* package array-0.5.3.0 */
#ifndef VERSION_array
#define VERSION_array "0.5.3.0"
#endif /* VERSION_array */
#ifndef MIN_VERSION_array
#define MIN_VERSION_array(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 3)
#endif /* MIN_VERSION_array */

/* package base-4.12.0.0 */
#ifndef VERSION_base
#define VERSION_base "4.12.0.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  12 || \
  (major1) == 4 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_base */

/* package blaze-builder-0.4.1.0 */
#ifndef VERSION_blaze_builder
#define VERSION_blaze_builder "0.4.1.0"
#endif /* VERSION_blaze_builder */
#ifndef MIN_VERSION_blaze_builder
#define MIN_VERSION_blaze_builder(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 1)
#endif /* MIN_VERSION_blaze_builder */

/* package bytestring-0.10.8.2 */
#ifndef VERSION_bytestring
#define VERSION_bytestring "0.10.8.2"
#endif /* VERSION_bytestring */
#ifndef MIN_VERSION_bytestring
#define MIN_VERSION_bytestring(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 8)
#endif /* MIN_VERSION_bytestring */

/* package containers-0.6.0.1 */
#ifndef VERSION_containers
#define VERSION_containers "0.6.0.1"
#endif /* VERSION_containers */
#ifndef MIN_VERSION_containers
#define MIN_VERSION_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  6 || \
  (major1) == 0 && (major2) == 6 && (minor) <= 0)
#endif /* MIN_VERSION_containers */

/* package data-default-0.7.1.1 */
#ifndef VERSION_data_default
#define VERSION_data_default "0.7.1.1"
#endif /* VERSION_data_default */
#ifndef MIN_VERSION_data_default
#define MIN_VERSION_data_default(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  7 || \
  (major1) == 0 && (major2) == 7 && (minor) <= 1)
#endif /* MIN_VERSION_data_default */

/* package directory-1.3.3.0 */
#ifndef VERSION_directory
#define VERSION_directory "1.3.3.0"
#endif /* VERSION_directory */
#ifndef MIN_VERSION_directory
#define MIN_VERSION_directory(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  3 || \
  (major1) == 1 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_directory */

/* package email-validate-2.3.2.11 */
#ifndef VERSION_email_validate
#define VERSION_email_validate "2.3.2.11"
#endif /* VERSION_email_validate */
#ifndef MIN_VERSION_email_validate
#define MIN_VERSION_email_validate(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 2)
#endif /* MIN_VERSION_email_validate */

/* package filepath-1.4.2.1 */
#ifndef VERSION_filepath
#define VERSION_filepath "1.4.2.1"
#endif /* VERSION_filepath */
#ifndef MIN_VERSION_filepath
#define MIN_VERSION_filepath(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  4 || \
  (major1) == 1 && (major2) == 4 && (minor) <= 2)
#endif /* MIN_VERSION_filepath */

/* package hedis-0.10.10 */
#ifndef VERSION_hedis
#define VERSION_hedis "0.10.10"
#endif /* VERSION_hedis */
#ifndef MIN_VERSION_hedis
#define MIN_VERSION_hedis(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 10)
#endif /* MIN_VERSION_hedis */

/* package http-conduit-2.3.7.1 */
#ifndef VERSION_http_conduit
#define VERSION_http_conduit "2.3.7.1"
#endif /* VERSION_http_conduit */
#ifndef MIN_VERSION_http_conduit
#define MIN_VERSION_http_conduit(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  3 || \
  (major1) == 2 && (major2) == 3 && (minor) <= 7)
#endif /* MIN_VERSION_http_conduit */

/* package http-types-0.12.3 */
#ifndef VERSION_http_types
#define VERSION_http_types "0.12.3"
#endif /* VERSION_http_types */
#ifndef MIN_VERSION_http_types
#define MIN_VERSION_http_types(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 3)
#endif /* MIN_VERSION_http_types */

/* package neat-interpolation-0.3.2.4 */
#ifndef VERSION_neat_interpolation
#define VERSION_neat_interpolation "0.3.2.4"
#endif /* VERSION_neat_interpolation */
#ifndef MIN_VERSION_neat_interpolation
#define MIN_VERSION_neat_interpolation(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 2)
#endif /* MIN_VERSION_neat_interpolation */

/* package network-uri-2.6.1.0 */
#ifndef VERSION_network_uri
#define VERSION_network_uri "2.6.1.0"
#endif /* VERSION_network_uri */
#ifndef MIN_VERSION_network_uri
#define MIN_VERSION_network_uri(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  6 || \
  (major1) == 2 && (major2) == 6 && (minor) <= 1)
#endif /* MIN_VERSION_network_uri */

/* package pretty-simple-2.2.0.1 */
#ifndef VERSION_pretty_simple
#define VERSION_pretty_simple "2.2.0.1"
#endif /* VERSION_pretty_simple */
#ifndef MIN_VERSION_pretty_simple
#define MIN_VERSION_pretty_simple(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  2 || \
  (major1) == 2 && (major2) == 2 && (minor) <= 0)
#endif /* MIN_VERSION_pretty_simple */

/* package process-1.6.5.0 */
#ifndef VERSION_process
#define VERSION_process "1.6.5.0"
#endif /* VERSION_process */
#ifndef MIN_VERSION_process
#define MIN_VERSION_process(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  6 || \
  (major1) == 1 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_VERSION_process */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package raw-strings-qq-1.1 */
#ifndef VERSION_raw_strings_qq
#define VERSION_raw_strings_qq "1.1"
#endif /* VERSION_raw_strings_qq */
#ifndef MIN_VERSION_raw_strings_qq
#define MIN_VERSION_raw_strings_qq(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_raw_strings_qq */

/* package regex-1.0.2.0 */
#ifndef VERSION_regex
#define VERSION_regex "1.0.2.0"
#endif /* VERSION_regex */
#ifndef MIN_VERSION_regex
#define MIN_VERSION_regex(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 2)
#endif /* MIN_VERSION_regex */

/* package regex-base-0.93.2 */
#ifndef VERSION_regex_base
#define VERSION_regex_base "0.93.2"
#endif /* VERSION_regex_base */
#ifndef MIN_VERSION_regex_base
#define MIN_VERSION_regex_base(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  93 || \
  (major1) == 0 && (major2) == 93 && (minor) <= 2)
#endif /* MIN_VERSION_regex_base */

/* package regex-compat-0.95.1 */
#ifndef VERSION_regex_compat
#define VERSION_regex_compat "0.95.1"
#endif /* VERSION_regex_compat */
#ifndef MIN_VERSION_regex_compat
#define MIN_VERSION_regex_compat(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  95 || \
  (major1) == 0 && (major2) == 95 && (minor) <= 1)
#endif /* MIN_VERSION_regex_compat */

/* package regex-posix-0.95.2 */
#ifndef VERSION_regex_posix
#define VERSION_regex_posix "0.95.2"
#endif /* VERSION_regex_posix */
#ifndef MIN_VERSION_regex_posix
#define MIN_VERSION_regex_posix(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  95 || \
  (major1) == 0 && (major2) == 95 && (minor) <= 2)
#endif /* MIN_VERSION_regex_posix */

/* package regex-tdfa-1.2.3.2 */
#ifndef VERSION_regex_tdfa
#define VERSION_regex_tdfa "1.2.3.2"
#endif /* VERSION_regex_tdfa */
#ifndef MIN_VERSION_regex_tdfa
#define MIN_VERSION_regex_tdfa(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_regex_tdfa */

/* package safe-0.3.17 */
#ifndef VERSION_safe
#define VERSION_safe "0.3.17"
#endif /* VERSION_safe */
#ifndef MIN_VERSION_safe
#define MIN_VERSION_safe(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 17)
#endif /* MIN_VERSION_safe */

/* package split-0.2.3.3 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.3"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */

/* package sqlite-simple-0.4.16.0 */
#ifndef VERSION_sqlite_simple
#define VERSION_sqlite_simple "0.4.16.0"
#endif /* VERSION_sqlite_simple */
#ifndef MIN_VERSION_sqlite_simple
#define MIN_VERSION_sqlite_simple(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  4 || \
  (major1) == 0 && (major2) == 4 && (minor) <= 16)
#endif /* MIN_VERSION_sqlite_simple */

/* package text-1.2.3.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package time-1.8.0.2 */
#ifndef VERSION_time
#define VERSION_time "1.8.0.2"
#endif /* VERSION_time */
#ifndef MIN_VERSION_time
#define MIN_VERSION_time(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  8 || \
  (major1) == 1 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_time */

/* package turtle-1.5.14 */
#ifndef VERSION_turtle
#define VERSION_turtle "1.5.14"
#endif /* VERSION_turtle */
#ifndef MIN_VERSION_turtle
#define MIN_VERSION_turtle(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  5 || \
  (major1) == 1 && (major2) == 5 && (minor) <= 14)
#endif /* MIN_VERSION_turtle */

/* package unix-2.7.2.2 */
#ifndef VERSION_unix
#define VERSION_unix "2.7.2.2"
#endif /* VERSION_unix */
#ifndef MIN_VERSION_unix
#define MIN_VERSION_unix(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  7 || \
  (major1) == 2 && (major2) == 7 && (minor) <= 2)
#endif /* MIN_VERSION_unix */

/* package unordered-containers-0.2.10.0 */
#ifndef VERSION_unordered_containers
#define VERSION_unordered_containers "0.2.10.0"
#endif /* VERSION_unordered_containers */
#ifndef MIN_VERSION_unordered_containers
#define MIN_VERSION_unordered_containers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 10)
#endif /* MIN_VERSION_unordered_containers */

/* package utf8-string-1.0.1.1 */
#ifndef VERSION_utf8_string
#define VERSION_utf8_string "1.0.1.1"
#endif /* VERSION_utf8_string */
#ifndef MIN_VERSION_utf8_string
#define MIN_VERSION_utf8_string(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  0 || \
  (major1) == 1 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_utf8_string */

/* package vector-0.12.0.3 */
#ifndef VERSION_vector
#define VERSION_vector "0.12.0.3"
#endif /* VERSION_vector */
#ifndef MIN_VERSION_vector
#define MIN_VERSION_vector(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 0)
#endif /* MIN_VERSION_vector */

/* package wai-3.2.2.1 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.2.1"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 2)
#endif /* MIN_VERSION_wai */

/* package wai-extra-3.0.26.1 */
#ifndef VERSION_wai_extra
#define VERSION_wai_extra "3.0.26.1"
#endif /* VERSION_wai_extra */
#ifndef MIN_VERSION_wai_extra
#define MIN_VERSION_wai_extra(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 26)
#endif /* MIN_VERSION_wai_extra */

/* package wai-predicates-0.10.0 */
#ifndef VERSION_wai_predicates
#define VERSION_wai_predicates "0.10.0"
#endif /* VERSION_wai_predicates */
#ifndef MIN_VERSION_wai_predicates
#define MIN_VERSION_wai_predicates(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  10 || \
  (major1) == 0 && (major2) == 10 && (minor) <= 0)
#endif /* MIN_VERSION_wai_predicates */

/* package wai-session-0.3.3 */
#ifndef VERSION_wai_session
#define VERSION_wai_session "0.3.3"
#endif /* VERSION_wai_session */
#ifndef MIN_VERSION_wai_session
#define MIN_VERSION_wai_session(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  3 || \
  (major1) == 0 && (major2) == 3 && (minor) <= 3)
#endif /* MIN_VERSION_wai_session */

/* package wai-util-0.8 */
#ifndef VERSION_wai_util
#define VERSION_wai_util "0.8"
#endif /* VERSION_wai_util */
#ifndef MIN_VERSION_wai_util
#define MIN_VERSION_wai_util(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  8 || \
  (major1) == 0 && (major2) == 8 && (minor) <= 0)
#endif /* MIN_VERSION_wai_util */

/* package wai-websockets-3.0.1.2 */
#ifndef VERSION_wai_websockets
#define VERSION_wai_websockets "3.0.1.2"
#endif /* VERSION_wai_websockets */
#ifndef MIN_VERSION_wai_websockets
#define MIN_VERSION_wai_websockets(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_wai_websockets */

/* package warp-3.2.28 */
#ifndef VERSION_warp
#define VERSION_warp "3.2.28"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 28)
#endif /* MIN_VERSION_warp */

/* package websockets-0.12.5.3 */
#ifndef VERSION_websockets
#define VERSION_websockets "0.12.5.3"
#endif /* VERSION_websockets */
#ifndef MIN_VERSION_websockets
#define MIN_VERSION_websockets(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 5)
#endif /* MIN_VERSION_websockets */

/* package word8-0.1.3 */
#ifndef VERSION_word8
#define VERSION_word8 "0.1.3"
#endif /* VERSION_word8 */
#ifndef MIN_VERSION_word8
#define MIN_VERSION_word8(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 3)
#endif /* MIN_VERSION_word8 */

/* tool gcc-4.2.1 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "4.2.1"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  2 || \
  (major1) == 4 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.6.5 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.6.5"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.6.5 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.6.5"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.22.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.22.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  22 || \
  (major1) == 2 && (major2) == 22 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.5 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.5"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.27.1 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.27.1"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  27 || \
  (major1) == 0 && (major2) == 27 && (minor) <= 1)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.6.5 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.6.5"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  6 || \
  (major1) == 8 && (major2) == 6 && (minor) <= 5)
#endif /* MIN_TOOL_VERSION_runghc */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "haskellwebapp2-0.1.0.0-7wnMB76tEPg2HSTm4DGwyf-haskellwebapp2"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
